# Generated by Django 6.0.5 on 2026-05-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('deadline', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=200)),
            ],
        ),
    ]
