# Generated by Django 6.0.5 on 2026-05-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchwork',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='research_pdfs/'),
        ),
    ]
